### ISSUE TITLE
INVALID PRIVATE KEY FORMAT

### ISSUE THREAD

**Issue by ayofimihan** [jaredonsolana/Bitcoin-Magic-Eden-Airdrop-Tool#1]
not accepting the WIF private key format so no api calls are even made. are you sure it works for btc

**Comment by jaredonsolana** [comment]
updated to support more kinds of keys

**Comment by ayofimihan** [comment]
still not working man, please be sure it works on btc and add your wallet address to readME for tips after claim. thanks
